### ISSUE TITLE
As a customer/guest, I want to select a shipping option of my choosing when checking out.

### ISSUE THREAD

**Issue by MosesDaCode** [KYH-Net23/ShippingProvider#1]
# Made by Mille Elfver, William Gross & Mousa Chammas

## **Acceptance Criterias**

- [x] New page with a list of available shipping options is displayed with the shipping company, delivery time and cost.
- [x] Customers can select their shipping option.
- [x] Shipping options get applied.

---
## **Activity Diagram**
[Plant Uml Link](https://www.plantuml.com/plantuml/duml/NP11JiGm34NtEOKFm0bcDeCu0bp0r6vhoOcjs2tgxKcHK65sqN_lwqT-H6BFhMhvUPJRsnPfbJiqt6N1v80qY5NSfIrGp5Ei1SpTAbYdOH8dYiQzt5v19H9i1jn7X9_AL_MtAG4auOe74vGloVLo9gkExNW1OfMT-m4fbG4R3HHv__E_OEKf0t9bwSyhGtp_dvopwAx2DE279IfububFi3bXdY3Il3ouqRZ8Dm00)

![Image](https://github.com/user-attachments/assets/56c72087-ecae-4e32-9fa8-2f39faaebb2d)
---
## **Tasks**

- [x] KYH-Net23/Rika#54
     - [x]  Implement a new shipping options page.
- [x] KYH-Net23/Rika#55
     - [x]  Implement a page to display a list of shipping options with delivery company name, delivery time, cost.
- [x] KYH-Net23/ProductsRepo#160
    - [x] Implement Postnord Delivery Service API.
    - [x] Implement DHL Delivery Service API.
    - [x] Implement Instabox Delivery Service API. 

---
## **Test Case Descriptions**

- [x] **Test case 1: Display all available shipping options**
- Prerequisites: 
   - Address form in the Order Details has been filled out.
- Steps:
1.  Customer/guest navigates to the Shipping Details page from Order Details.
 - Expected result:
   - All available shipping options are displayed for the customer/guest.

- [x] **Test case 2: Apply selected shipping option**
- Prerequisites: 
  - Address form in the Order Details has been filled out.
- Steps:
1.    Customer/guest navigates to the Shipping Details page from Order Details.
2.    All available shipping options are displayed for the customer/guest.
3.    Customer/guest selects a shipping option.

Expected result:
  - Selected shipping option is applied to the order.

---
