### ISSUE TITLE
As a customer/guest, I want to see the estimated delivery date for each shipping method so that I know when to expect my order.

### ISSUE THREAD

**Issue by MosesDaCode** [KYH-Net23/ShippingProvider#5]
# Made by Mille Elfver, William Gross & Mousa Chammas

## **Acceptance Criterias**

- [x] Customer is viewing shipping options.
- [x] Customers should see estimated delivery time based on the shipping method.
- [x] Estimated delivery date should be updated when the customer changes shipping method.
---
## **Activity Diagram**
[Plant Uml Link](https://www.plantuml.com/plantuml/duml/NT1DReKm30JWVKunIxZ2O_EadYGbyy1gi2FizEVsZRgYx4QQJvOrJuzyHZzg-WlfyTOzxE29J-4Nx2mZ5aQMwikbNQki7mvJ-2wjYMuu6BiLntkFCFs7TpCdyjqkILwOBYphHh-h6R5JCVtGv_IubTWOZjvA3evxh4vCQdEY5dbTVyYArJH4En46vNV0Wsr9GxJqf9Onmoy0)
![Image](https://github.com/user-attachments/assets/1c3ca12f-b80d-4d18-856e-5f639eb1a4f5)
---

## **Tasks**

- [x] KYH-Net23/Rika#64
  - [x] Create a view that displays different shipping methods with estimated delivery dates.
- [x] KYH-Net23/ProductsRepo#161
  - [x] Add logic to update the displayed shipping methods estimated delivery date when the user selects or changes a shipping method.
---

## **Test Case Descriptions**
- [x] **Test case 1: Verify that available shipping methods and estimated delivery dates display correctly.**
Prerequisites: 
  - User has items in the shopping cart and is view the order details

Steps:
1. Click on the checkout button.
2. View the available shipping methods.

Expected result:
  - Each shipping method is displayed with the correct estimated delivery date.

- [x] **Test case 2: Verify that the estimated delivery date updates correctly when picking different methods.**
Prerequisites:
  - User has picked a shipping method.

Steps:
1. select a shipping method.
2. See the estimated delivery date.
3. Change to another shipping method.

Expected result:
  - The estimated delivery date is updated to a new estimated delivery date.
